// GENERATED by tool/cas_corpus_verify.py — DO NOT EDIT.
// Source of truth: test/data/cas_corpus.json (SymPy-certified).
// Embedded as a string so integration_test runners need no file IO.

const String kCasCorpusJson = '''
{
  "comment": [
    "CAS regression corpus — single source of truth for the verified",
    "engine-behavior tests (roadmap C1). Every case is certified by an",
    "independent open-source CAS (SymPy) via tool/cas_corpus_verify.py,",
    "which also regenerates test/cas_corpus_data.dart. Edit THIS file,",
    "then run:  python3 tool/cas_corpus_verify.py",
    "",
    "Fields: op — engine operation; input/var/args — operation input;",
    "expected — engine-syntax expected result (expression, root list, or",
    "numeric value); runners — 'native' (integration_test, real SymEngine",
    "bridge) and/or 'dart' (plain flutter test, pure-Dart fallback paths);",
    "check — equiv (numeric-sampling equivalence), roots (root-set match),",
    "value (numeric tolerance), antiderivative (difference-is-constant),",
    "exact (normalized string equality). knownGap — the engine is known to",
    "get this case wrong; runners assert the failure still reproduces."
  ],
  "cases": [
    {
      "id": "eval_arith",
      "op": "evaluate",
      "input": "2 + 3*4",
      "expected": "14",
      "runners": [
        "native"
      ],
      "check": "value"
    },
    {
      "id": "eval_pow",
      "op": "evaluate",
      "input": "2^10",
      "expected": "1024",
      "runners": [
        "native"
      ],
      "check": "value"
    },
    {
      "id": "eval_rational",
      "op": "evaluate",
      "input": "1/3 + 1/6",
      "expected": "1/2",
      "runners": [
        "native"
      ],
      "check": "value"
    },
    {
      "id": "eval_rational_pow",
      "op": "evaluate",
      "input": "(2/3)^2",
      "expected": "4/9",
      "runners": [
        "native"
      ],
      "check": "value"
    },
    {
      "id": "eval_sqrt",
      "op": "evaluate",
      "input": "sqrt(16)",
      "expected": "4",
      "runners": [
        "native"
      ],
      "check": "value"
    },
    {
      "id": "eval_bigint",
      "op": "evaluate",
      "input": "2^100",
      "expected": "1267650600228229401496703205376",
      "runners": [
        "native"
      ],
      "check": "value"
    },
    {
      "id": "expand_binomial_sq",
      "op": "expand",
      "input": "(x+1)^2",
      "var": "x",
      "expected": "x^2 + 2*x + 1",
      "runners": [
        "dart",
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "expand_product",
      "op": "expand",
      "input": "(x+2)*(x-3)",
      "var": "x",
      "expected": "x^2 - x - 6",
      "runners": [
        "dart",
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "expand_cube",
      "op": "expand",
      "input": "(x+1)^3",
      "var": "x",
      "expected": "x^3 + 3*x^2 + 3*x + 1",
      "runners": [
        "dart",
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "expand_nonmonic",
      "op": "expand",
      "input": "(2*x-1)*(3*x+4)",
      "var": "x",
      "expected": "6*x^2 + 5*x - 4",
      "runners": [
        "dart",
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "expand_multivar",
      "op": "expand",
      "input": "(x+y)^2",
      "var": "x",
      "vars": [
        "x",
        "y"
      ],
      "expected": "x^2 + 2*x*y + y^2",
      "runners": [
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "expand_cubic_identity",
      "op": "expand",
      "input": "(x-1)*(x^2+x+1)",
      "var": "x",
      "expected": "x^3 - 1",
      "runners": [
        "dart",
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "factor_diff_squares",
      "op": "factor",
      "input": "x^2 - 1",
      "var": "x",
      "expected": "(x-1)*(x+1)",
      "runners": [
        "dart",
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "factor_sophie_germain",
      "op": "factor",
      "input": "x^4 + 4",
      "var": "x",
      "expected": "(x^2 - 2*x + 2)*(x^2 + 2*x + 2)",
      "runners": [
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "factor_nonmonic",
      "op": "factor",
      "input": "6*x^2 + 5*x - 4",
      "var": "x",
      "expected": "(2*x - 1)*(3*x + 4)",
      "runners": [
        "dart",
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "factor_repeated",
      "op": "factor",
      "input": "x^2 - 2*x + 1",
      "var": "x",
      "expected": "(x-1)^2",
      "runners": [
        "dart",
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "factor_common_x",
      "op": "factor",
      "input": "x^3 - x",
      "var": "x",
      "expected": "x*(x-1)*(x+1)",
      "runners": [
        "dart",
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "factor_multivar_dos",
      "op": "factor",
      "input": "x^2 - y^2",
      "var": "x",
      "vars": [
        "x",
        "y"
      ],
      "expected": "(x-y)*(x+y)",
      "runners": [
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "factor_multivar_grouping",
      "op": "factor",
      "input": "x*y + x + y + 1",
      "var": "x",
      "vars": [
        "x",
        "y"
      ],
      "expected": "(x+1)*(y+1)",
      "runners": [
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "simplify_rational_cancel",
      "op": "simplify",
      "input": "(x^2 - 1)/(x - 1)",
      "var": "x",
      "expected": "x + 1",
      "runners": [
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "simplify_rational_cancel_sq",
      "op": "simplify",
      "input": "(x^2 + 2*x + 1)/(x + 1)",
      "var": "x",
      "expected": "x + 1",
      "runners": [
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "simplify_like_terms",
      "op": "simplify",
      "input": "2*x + 3*x",
      "var": "x",
      "expected": "5*x",
      "runners": [
        "dart",
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "simplify_power_collect",
      "op": "simplify",
      "input": "x*x*x",
      "var": "x",
      "expected": "x^3",
      "runners": [
        "dart",
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "solve_linear",
      "op": "solve",
      "input": "2*x + 3",
      "var": "x",
      "expected": [
        "-3/2"
      ],
      "runners": [
        "dart",
        "native"
      ],
      "check": "roots"
    },
    {
      "id": "solve_quadratic_int",
      "op": "solve",
      "input": "x^2 - 4",
      "var": "x",
      "expected": [
        "2",
        "-2"
      ],
      "runners": [
        "dart",
        "native"
      ],
      "check": "roots"
    },
    {
      "id": "solve_golden_ratio",
      "op": "solve",
      "input": "x^2 - x - 1",
      "var": "x",
      "expected": [
        "1/2 + sqrt(5)/2",
        "1/2 - sqrt(5)/2"
      ],
      "runners": [
        "dart",
        "native"
      ],
      "check": "roots"
    },
    {
      "id": "solve_surd",
      "op": "solve",
      "input": "x^2 - 2",
      "var": "x",
      "expected": [
        "sqrt(2)",
        "-sqrt(2)"
      ],
      "runners": [
        "dart",
        "native"
      ],
      "check": "roots"
    },
    {
      "id": "solve_cubic_factorable",
      "op": "solve",
      "input": "x^3 - 6*x^2 + 11*x - 6",
      "var": "x",
      "expected": [
        "1",
        "2",
        "3"
      ],
      "runners": [
        "native"
      ],
      "check": "roots"
    },
    {
      "id": "diff_power",
      "op": "differentiate",
      "input": "x^3",
      "var": "x",
      "expected": "3*x^2",
      "runners": [
        "dart",
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "diff_poly",
      "op": "differentiate",
      "input": "x^2 + 3*x + 5",
      "var": "x",
      "expected": "2*x + 3",
      "runners": [
        "dart",
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "diff_sin",
      "op": "differentiate",
      "input": "sin(x)",
      "var": "x",
      "expected": "cos(x)",
      "runners": [
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "diff_chain",
      "op": "differentiate",
      "input": "sin(x^2)",
      "var": "x",
      "expected": "2*x*cos(x^2)",
      "runners": [
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "diff_product",
      "op": "differentiate",
      "input": "x*exp(x)",
      "var": "x",
      "expected": "exp(x) + x*exp(x)",
      "runners": [
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "diff_log",
      "op": "differentiate",
      "input": "log(x)",
      "var": "x",
      "expected": "1/x",
      "runners": [
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "diff_quotient",
      "op": "differentiate",
      "input": "x/(x + 1)",
      "var": "x",
      "expected": "1/(x + 1)^2",
      "runners": [
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "diff_tan",
      "op": "differentiate",
      "input": "tan(x)",
      "var": "x",
      "expected": "1 + tan(x)^2",
      "runners": [
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "subs_numeric",
      "op": "substitute",
      "input": "x^2 + 1",
      "var": "x",
      "value": "3",
      "expected": "10",
      "runners": [
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "subs_partial",
      "op": "substitute",
      "input": "x^2 + y",
      "var": "x",
      "value": "2",
      "vars": [
        "y"
      ],
      "expected": "4 + y",
      "runners": [
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "subs_trig_zero",
      "op": "substitute",
      "input": "sin(x)",
      "var": "x",
      "value": "0",
      "expected": "0",
      "runners": [
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "gcd_composite",
      "op": "gcd",
      "args": [
        "48",
        "36"
      ],
      "expected": "12",
      "runners": [
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "gcd_coprime",
      "op": "gcd",
      "args": [
        "17",
        "5"
      ],
      "expected": "1",
      "runners": [
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "lcm_basic",
      "op": "lcm",
      "args": [
        "6",
        "8"
      ],
      "expected": "24",
      "runners": [
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "int_power",
      "op": "integrate",
      "input": "x^2",
      "var": "x",
      "expected": "x^3/3",
      "runners": [
        "dart",
        "native"
      ],
      "check": "antiderivative"
    },
    {
      "id": "int_linear",
      "op": "integrate",
      "input": "2*x + 3",
      "var": "x",
      "expected": "x^2 + 3*x",
      "runners": [
        "dart",
        "native"
      ],
      "check": "antiderivative"
    },
    {
      "id": "int_sin",
      "op": "integrate",
      "input": "sin(x)",
      "var": "x",
      "expected": "-cos(x)",
      "runners": [
        "native"
      ],
      "check": "antiderivative"
    },
    {
      "id": "int_cos",
      "op": "integrate",
      "input": "cos(x)",
      "var": "x",
      "expected": "sin(x)",
      "runners": [
        "native"
      ],
      "check": "antiderivative"
    },
    {
      "id": "int_exp",
      "op": "integrate",
      "input": "exp(x)",
      "var": "x",
      "expected": "exp(x)",
      "runners": [
        "native"
      ],
      "check": "antiderivative"
    },
    {
      "id": "int_by_parts",
      "op": "integrate",
      "input": "x*exp(x)",
      "var": "x",
      "expected": "(x - 1)*exp(x)",
      "runners": [
        "native"
      ],
      "check": "antiderivative"
    },
    {
      "id": "int_by_parts_trig",
      "op": "integrate",
      "input": "x*sin(x)",
      "var": "x",
      "expected": "sin(x) - x*cos(x)",
      "runners": [
        "native"
      ],
      "check": "antiderivative"
    },
    {
      "id": "intdef_power",
      "op": "integrate_def",
      "input": "x^2",
      "var": "x",
      "lo": "0",
      "hi": "1",
      "expected": "1/3",
      "runners": [
        "native"
      ],
      "check": "value"
    },
    {
      "id": "intdef_sin_halfperiod",
      "op": "integrate_def",
      "input": "sin(x)",
      "var": "x",
      "lo": "0",
      "hi": "pi",
      "expected": "2",
      "runners": [
        "native"
      ],
      "check": "value"
    },
    {
      "id": "intdef_exp",
      "op": "integrate_def",
      "input": "exp(x)",
      "var": "x",
      "lo": "0",
      "hi": "1",
      "expected": "e - 1",
      "runners": [
        "native"
      ],
      "check": "value"
    },
    {
      "id": "limit_sinc",
      "op": "limit",
      "input": "sin(x)/x",
      "var": "x",
      "point": "0",
      "expected": "1",
      "runners": [
        "native"
      ],
      "check": "value"
    },
    {
      "id": "limit_removable",
      "op": "limit",
      "input": "(x^2 - 1)/(x - 1)",
      "var": "x",
      "point": "1",
      "expected": "2",
      "runners": [
        "native"
      ],
      "check": "value"
    },
    {
      "id": "limit_reciprocal_inf",
      "op": "limit",
      "input": "1/x",
      "var": "x",
      "point": "oo",
      "expected": "0",
      "runners": [
        "native"
      ],
      "check": "value"
    },
    {
      "id": "limit_rational_inf",
      "op": "limit",
      "input": "(3*x^2 + 1)/(2*x^2 + x)",
      "var": "x",
      "point": "oo",
      "expected": "3/2",
      "runners": [
        "native"
      ],
      "check": "value"
    },
    {
      "id": "limit_exp_decay",
      "op": "limit",
      "input": "exp(-x)",
      "var": "x",
      "point": "oo",
      "expected": "0",
      "runners": [
        "native"
      ],
      "check": "value"
    },
    {
      "id": "limit_cos_quadratic",
      "op": "limit",
      "input": "(1 - cos(x))/x^2",
      "var": "x",
      "point": "0",
      "expected": "1/2",
      "runners": [
        "native"
      ],
      "check": "value",
      "knownGap": "numeric-limit fallback returns ~0.4996 (cancellation noise); symbolic tiers do not resolve this form yet — roadmap C3"
    },
    {
      "id": "series_sin",
      "op": "series",
      "input": "sin(x)",
      "var": "x",
      "point": "0",
      "order": 8,
      "expected": "x - x^3/6 + x^5/120 - x^7/5040",
      "runners": [
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "series_exp",
      "op": "series",
      "input": "exp(x)",
      "var": "x",
      "point": "0",
      "order": 4,
      "expected": "1 + x + x^2/2 + x^3/6",
      "runners": [
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "series_geometric",
      "op": "series",
      "input": "1/(1 - x)",
      "var": "x",
      "point": "0",
      "order": 5,
      "expected": "1 + x + x^2 + x^3 + x^4",
      "runners": [
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "series_cos",
      "op": "series",
      "input": "cos(x)",
      "var": "x",
      "point": "0",
      "order": 7,
      "expected": "1 - x^2/2 + x^4/24 - x^6/720",
      "runners": [
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "series_log_about_1",
      "op": "series",
      "input": "log(x)",
      "var": "x",
      "point": "1",
      "order": 4,
      "expected": "(x - 1) - (x - 1)^2/2 + (x - 1)^3/3",
      "runners": [
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "linsolve_2x2",
      "op": "linsolve",
      "equations": [
        "x + y = 3",
        "x - y = 1"
      ],
      "symbols": [
        "x",
        "y"
      ],
      "expected": "x = 2, y = 1",
      "runners": [
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "linsolve_3x3",
      "op": "linsolve",
      "equations": [
        "2*x + y = 5",
        "x - z = 1",
        "y + z = 2"
      ],
      "symbols": [
        "x",
        "y",
        "z"
      ],
      "expected": "x = 2, y = 1, z = 1",
      "runners": [
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "linsolve_rational",
      "op": "linsolve",
      "equations": [
        "2*x = 3"
      ],
      "symbols": [
        "x"
      ],
      "expected": "x = 3/2",
      "runners": [
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "simplify_pythagorean",
      "op": "simplify",
      "input": "sin(x)^2 + cos(x)^2",
      "var": "x",
      "expected": "1",
      "runners": [
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "simplify_pythagorean_scaled",
      "op": "simplify",
      "input": "3*sin(x)^2 + 3*cos(x)^2",
      "var": "x",
      "expected": "3",
      "runners": [
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "simplify_double_angle",
      "op": "simplify",
      "input": "2*sin(x)*cos(x)",
      "var": "x",
      "expected": "sin(2*x)",
      "runners": [
        "native"
      ],
      "check": "equiv"
    },
    {
      "id": "ineq_quadratic_gt",
      "op": "solve_ineq",
      "input": "x^2 - 4 > 0",
      "var": "x",
      "expected": "x < -2 ∨ x > 2",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "ineq_quadratic_le",
      "op": "solve_ineq",
      "input": "x^2 - 4 <= 0",
      "var": "x",
      "expected": "-2 ≤ x ≤ 2",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "ineq_linear_lt",
      "op": "solve_ineq",
      "input": "2*x + 3 < 0",
      "var": "x",
      "expected": "x < -3/2",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "ineq_double_root_gt",
      "op": "solve_ineq",
      "input": "x^2 - 2*x + 1 > 0",
      "var": "x",
      "expected": "x ≠ 1",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "ineq_double_root_le",
      "op": "solve_ineq",
      "input": "x^2 - 2*x + 1 <= 0",
      "var": "x",
      "expected": "x = 1",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "ineq_always_true",
      "op": "solve_ineq",
      "input": "x^2 + 1 > 0",
      "var": "x",
      "expected": "x ∈ ℝ",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "ineq_never_true",
      "op": "solve_ineq",
      "input": "x^2 + 1 < 0",
      "var": "x",
      "expected": "x ∈ ∅",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "ineq_surd_ge",
      "op": "solve_ineq",
      "input": "x^2 - 2 >= 0",
      "var": "x",
      "expected": "x ≤ -sqrt(2) ∨ x ≥ sqrt(2)",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "int_rat_partial_fractions",
      "op": "integrate",
      "input": "1/(x^2 - 1)",
      "var": "x",
      "expected": "log(x - 1)/2 - log(x + 1)/2",
      "runners": [
        "dart",
        "native"
      ],
      "check": "antiderivative"
    },
    {
      "id": "int_rat_atan",
      "op": "integrate",
      "input": "1/(x^2 + x + 1)",
      "var": "x",
      "expected": "2*atan((2*x + 1)/sqrt(3))/sqrt(3)",
      "runners": [
        "dart",
        "native"
      ],
      "check": "antiderivative"
    },
    {
      "id": "int_rat_hermite",
      "op": "integrate",
      "input": "1/(x^2 - 2*x + 1)",
      "var": "x",
      "expected": "-1/(x - 1)",
      "runners": [
        "dart",
        "native"
      ],
      "check": "antiderivative"
    },
    {
      "id": "int_rat_polypart",
      "op": "integrate",
      "input": "(x^3 + 1)/x^2",
      "var": "x",
      "expected": "x^2/2 - 1/x",
      "runners": [
        "dart",
        "native"
      ],
      "check": "antiderivative"
    },
    {
      "id": "int_rat_mixed",
      "op": "integrate",
      "input": "(2*x + 3)/(x^2 + x + 1)",
      "var": "x",
      "expected": "log(x^2 + x + 1) + 4*atan((2*x + 1)/sqrt(3))/sqrt(3)",
      "runners": [
        "dart",
        "native"
      ],
      "check": "antiderivative"
    },
    {
      "id": "int_rat_multiplicity",
      "op": "integrate",
      "input": "1/(x - 2)^3",
      "var": "x",
      "expected": "-1/(2*(x - 2)^2)",
      "runners": [
        "dart",
        "native"
      ],
      "check": "antiderivative"
    },
    {
      "id": "int_rat_quartic",
      "op": "integrate",
      "input": "1/(x^4 - 1)",
      "var": "x",
      "expected": "log(x - 1)/4 - log(x + 1)/4 - atan(x)/2",
      "runners": [
        "dart",
        "native"
      ],
      "check": "antiderivative"
    },
    {
      "id": "int_rat_surd",
      "op": "integrate",
      "input": "1/(x^2 - 1/3)",
      "var": "x",
      "expected": "sqrt(3)*log((x - sqrt(3)/3)/(x + sqrt(3)/3))/2",
      "runners": [
        "dart",
        "native"
      ],
      "check": "antiderivative"
    },
    {
      "id": "dsolve_growth",
      "op": "dsolve",
      "input": "y' = 3*y",
      "expected": "y = C1*exp(3*x)",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "dsolve_distinct_real",
      "op": "dsolve",
      "input": "y'' + 3*y' + 2*y = 0",
      "expected": "y = C1*exp(-x) + C2*exp(-2*x)",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "dsolve_double_root",
      "op": "dsolve",
      "input": "y'' - 2*y' + y = 0",
      "expected": "y = (C1 + C2*x)*exp(x)",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "dsolve_complex",
      "op": "dsolve",
      "input": "y'' + 2*y' + 5*y = 0",
      "expected": "y = exp(-x)*(C1*cos(2*x) + C2*sin(2*x))",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "dsolve_poly_forcing",
      "op": "dsolve",
      "input": "y' + y = x^2",
      "expected": "y = C1*exp(-x) + x^2 - 2*x + 2",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "dsolve_exp_forcing",
      "op": "dsolve",
      "input": "y'' - y = exp(2*x)",
      "expected": "y = C1*exp(x) + C2*exp(-x) + 1/3*exp(2*x)",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "dsolve_exp_resonance",
      "op": "dsolve",
      "input": "y' - y = exp(x)",
      "expected": "y = C1*exp(x) + x*exp(x)",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "dsolve_trig_forcing",
      "op": "dsolve",
      "input": "y'' + y = sin(2*x)",
      "expected": "y = C1*cos(x) + C2*sin(x) - 1/3*sin(2*x)",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "dsolve_sep_linear_var",
      "op": "dsolve",
      "input": "y' = x*y",
      "expected": "y = C1*exp(1/2*x^2)",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "dsolve_power_law",
      "op": "dsolve",
      "input": "y' = 2*y/x",
      "expected": "y = C1*x^2",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "dsolve_sep_reciprocal_sq",
      "op": "dsolve",
      "input": "y' = -y^2",
      "expected": "y = 1/(C1 + x)",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "dsolve_sep_implicit",
      "op": "dsolve",
      "input": "y' = x/y",
      "expected": "y^2 = x^2 + C1",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "dsolve_linear_var_poly",
      "op": "dsolve",
      "input": "y' + 2*y/x = x",
      "expected": "y = 1/4*x^2 + C1/x^2",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "dsolve_linear_var_const",
      "op": "dsolve",
      "input": "y' + y/x = 1",
      "expected": "y = 1/2*x + C1/x",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "dsolve_linear_var_homog",
      "op": "dsolve",
      "input": "y' + 2*y/x = 0",
      "expected": "y = C1/x^2",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "dsolve_bernoulli_logistic",
      "op": "dsolve",
      "input": "y' + y = y^2",
      "expected": "y = 1/(C1*exp(x) + 1)",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "dsolve_bernoulli_decay",
      "op": "dsolve",
      "input": "y' - y = y^2",
      "expected": "y = 1/(C1*exp(-x) - 1)",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "dsolve_bernoulli_cubic",
      "op": "dsolve",
      "input": "y' + 2*y = y^3",
      "expected": "y = 1/sqrt(C1*exp(4*x) + 1/2)",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "dsolve_exact_symmetric",
      "op": "dsolve",
      "input": "(2*x + y) + (x + 2*y)*y' = 0",
      "expected": "x^2 + x*y + y^2 = C1",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "dsolve_exact_mixed",
      "op": "dsolve",
      "input": "(2*x*y + 3) + (x^2 - 1)*y' = 0",
      "expected": "x^2*y + 3*x - y = C1",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "dsolve_exact_cubic",
      "op": "dsolve",
      "input": "(3*x^2 + 2*y) + (2*x + 4*y)*y' = 0",
      "expected": "x^3 + 2*x*y + 2*y^2 = C1",
      "runners": [
        "dart",
        "native"
      ],
      "check": "exact"
    },
    {
      "id": "int_rt_cubic",
      "op": "integrate",
      "input": "(3*x^2 + 1)/(x^3 + x + 1)",
      "var": "x",
      "expected": "log(x^3 + x + 1)",
      "runners": [
        "dart",
        "native"
      ],
      "check": "antiderivative"
    },
    {
      "id": "int_rt_quartic",
      "op": "integrate",
      "input": "(4*x^3 + 1)/(x^4 + x + 5)",
      "var": "x",
      "expected": "log(x^4 + x + 5)",
      "runners": [
        "dart",
        "native"
      ],
      "check": "antiderivative"
    }
  ]
}
''';
