import 'package:flutter/material.dart';

/// Strings for the connected entry, graph and provider workflows.
/// Keep every locale exhaustive; coverage is enforced by unit tests.
enum WorkflowLabel {
  historyCompare,
  historyChanges,
  historyNoChanges,
  historyRestoreNotice,
  historyRestore,
  historyLimits,
  historyEmpty,
  historySave,
  historyBeforeRestore,
  historyCompareButton,
  cancel,
  exportSnapshot,
  exportFailed,
  exportSave,
  exportUndefined,

  exploreWorksheet,
  connectedWorksheetName,
  worksheetGraph,
  worksheetHistory,
  worksheetExport,
  worksheetGraphFull,
  worksheetLinkFailed,
  resultDetails,
  resultExact,
  resultApproximate,
  resultSymbolic,
  resultComputed,
  resultUnsupported,
  resultUnchanged,
  resultUnknownPrecision,
  methodInteger,
  methodPolynomial,
  methodExpansionFallback,
  methodRational,
  methodRules,
  methodFundamental,
  methodSimpson,
  methodNumeric,
  methodSymbolic,
  methodSimplification,
  methodCalendar,
  methodUnits,

  editExpression,
  mathPreview,
  expression,
  resetFocus,
  backspace,
  cursorLeft,
  cursorRight,
  evaluate,
  linkedSource,
  sourceExplanation,
  editVariable,
  detachSource,
  openSource,
  close,
  mathAssistance,
  configured,
  configureProvider,
  mathQuestion,
  questionHint,
  providerNotice,
  reviewExpression,
  translatedExpression,
  cancelRequest,
  cancelled,
  translate,
  retry,
  useCalculator,
  clarification,
  updatingResults,
  resultsFailed,
  calculationProgress,
  cancelCalculation,
  calculationStopped,
}

class WorkflowLocalizations {
  const WorkflowLocalizations(this.language);
  final String language;
  static WorkflowLocalizations of(BuildContext context) =>
      WorkflowLocalizations(Localizations.localeOf(context).languageCode);
  String text(WorkflowLabel key, [String value = '']) =>
      (translations[language] ?? translations['en']!)[key]!
          .replaceAll('{value}', value);

  static const translations = <String, Map<WorkflowLabel, String>>{
    'en': {
      WorkflowLabel.historyCompare: 'Compare checkpoint',
      WorkflowLabel.historyChanges: 'Changes since this checkpoint:',
      WorkflowLabel.historyNoChanges: 'No source changes',
      WorkflowLabel.historyRestoreNotice: 'Restore saves a checkpoint of your current work first and recalculates results.',
      WorkflowLabel.historyRestore: 'Restore checkpoint',
      WorkflowLabel.historyLimits: 'Up to 20 checkpoints per document, 100 in total, within 1 MB. Older checkpoints expire as the limit is reached.',
      WorkflowLabel.historyEmpty: 'No checkpoints yet. Save one to keep a version of this worksheet.',
      WorkflowLabel.historySave: 'Save checkpoint',
      WorkflowLabel.historyBeforeRestore: 'Before restore',
      WorkflowLabel.historyCompareButton: 'Compare',
      WorkflowLabel.cancel: 'Cancel',
      WorkflowLabel.exportSnapshot: 'Snapshot of calculations and linked graphs. Graph x/y range: -5 to 5; table x range: -5 to 5.',
      WorkflowLabel.exportFailed: 'Export failed: {value}',
      WorkflowLabel.exportSave: 'Save {value}',
      WorkflowLabel.exportUndefined: 'Undefined',

      WorkflowLabel.exploreWorksheet: 'Explore a linked worksheet',
      WorkflowLabel.connectedWorksheetName: 'Explore a function',
      WorkflowLabel.worksheetGraph: 'View linked graph',
      WorkflowLabel.worksheetHistory: 'Document history',
      WorkflowLabel.worksheetExport: 'Worksheet export preview',
      WorkflowLabel.worksheetGraphFull: 'Worksheet created. Graph slots are full; clear a slot, then plot the function line.',
      WorkflowLabel.worksheetLinkFailed: 'Worksheet created, but the graph could not be linked: {value}',

      WorkflowLabel.calculationProgress: 'Updating results: {value}',
      WorkflowLabel.cancelCalculation: 'Cancel calculation',
      WorkflowLabel.calculationStopped:
          'Calculation stopped. Completed results are kept.',
      WorkflowLabel.methodExpansionFallback:
          'Polynomial expansion fallback; full simplification unavailable',
      WorkflowLabel.resultDetails: 'Result details',
      WorkflowLabel.resultExact: 'Exact',
      WorkflowLabel.resultApproximate: 'Approximate',
      WorkflowLabel.resultSymbolic: 'Symbolic',
      WorkflowLabel.resultComputed: 'Computed',
      WorkflowLabel.resultUnsupported: 'Unsupported',
      WorkflowLabel.resultUnchanged:
          'No change was produced. This does not prove the expression cannot simplify further.',
      WorkflowLabel.resultUnknownPrecision:
          'This operation did not report its precision.',
      WorkflowLabel.methodInteger: 'Integer arithmetic',
      WorkflowLabel.methodPolynomial: 'Exact polynomial integration',
      WorkflowLabel.methodRational: 'Rational-function integration',
      WorkflowLabel.methodRules: 'Symbolic integration rules',
      WorkflowLabel.methodFundamental: 'Antiderivative evaluated at the bounds',
      WorkflowLabel.methodSimpson: 'Numerical integration (Simpson’s rule)',
      WorkflowLabel.methodNumeric: 'Floating-point evaluation',
      WorkflowLabel.methodSymbolic: 'Expression evaluation',
      WorkflowLabel.methodSimplification: 'Simplification',
      WorkflowLabel.methodCalendar: 'Calendar arithmetic',
      WorkflowLabel.methodUnits: 'Unit conversion',
      WorkflowLabel.updatingResults: 'Updating results. You can keep editing.',
      WorkflowLabel.resultsFailed:
          'Could not update all results. Retry the calculation.',
      WorkflowLabel.editExpression: 'Edit expression',
      WorkflowLabel.mathPreview: 'Math preview',
      WorkflowLabel.expression: 'Expression',
      WorkflowLabel.resetFocus: 'Reset keyboard focus',
      WorkflowLabel.backspace: 'Backspace',
      WorkflowLabel.cursorLeft: 'Move cursor left',
      WorkflowLabel.cursorRight: 'Move cursor right',
      WorkflowLabel.evaluate: 'Evaluate',
      WorkflowLabel.linkedSource: 'Linked source for Y{value}',
      WorkflowLabel.sourceExplanation:
          'x is the graph variable. Other values come from the source document.',
      WorkflowLabel.editVariable: 'Edit {value}',
      WorkflowLabel.detachSource: 'Detach source',
      WorkflowLabel.openSource: 'Open source',
      WorkflowLabel.close: 'Close',
      WorkflowLabel.mathAssistance: 'Math assistance',
      WorkflowLabel.configured:
          'Configured: {value}. Connection is verified after a successful request.',
      WorkflowLabel.configureProvider:
          'Configure a provider endpoint and model in CrispAssist settings.',
      WorkflowLabel.mathQuestion: 'Math question',
      WorkflowLabel.questionHint: 'e.g. Integrate x squared',
      WorkflowLabel.providerNotice:
          'This sends your question to the configured provider. Review its translation; the calculator computes the result.',
      WorkflowLabel.reviewExpression:
          'Provider responded. Review or edit this expression:',
      WorkflowLabel.translatedExpression: 'Translated expression',
      WorkflowLabel.cancelRequest: 'Cancel request',
      WorkflowLabel.cancelled: 'Request cancelled. You can retry.',
      WorkflowLabel.translate: 'Translate',
      WorkflowLabel.retry: 'Retry',
      WorkflowLabel.useCalculator: 'Use in calculator',
      WorkflowLabel.clarification: 'More information needed: {value}',
    },
    'de': {
      WorkflowLabel.historyCompare: 'Stand vergleichen',
      WorkflowLabel.historyChanges: 'Änderungen seit diesem Stand:',
      WorkflowLabel.historyNoChanges: 'Keine Quelltextänderungen',
      WorkflowLabel.historyRestoreNotice: 'Vor der Wiederherstellung wird Ihre aktuelle Arbeit gesichert und anschließend neu berechnet.',
      WorkflowLabel.historyRestore: 'Stand wiederherstellen',
      WorkflowLabel.historyLimits: 'Bis zu 20 Stände je Dokument, insgesamt 100, innerhalb von 1 MB. Bei Erreichen der Grenze entfallen ältere Stände.',
      WorkflowLabel.historyEmpty: 'Noch keine Stände. Speichern Sie einen Stand, um eine Version dieses Arbeitsblatts zu behalten.',
      WorkflowLabel.historySave: 'Stand speichern',
      WorkflowLabel.historyBeforeRestore: 'Vor Wiederherstellung',
      WorkflowLabel.historyCompareButton: 'Vergleichen',
      WorkflowLabel.cancel: 'Abbrechen',
      WorkflowLabel.exportSnapshot: 'Momentaufnahme der Berechnungen und verknüpften Graphen. Graphenbereich x/y: -5 bis 5; Tabellenbereich x: -5 bis 5.',
      WorkflowLabel.exportFailed: 'Export fehlgeschlagen: {value}',
      WorkflowLabel.exportSave: '{value} speichern',
      WorkflowLabel.exportUndefined: 'Nicht definiert',

      WorkflowLabel.exploreWorksheet: 'Verknüpftes Arbeitsblatt erkunden',
      WorkflowLabel.connectedWorksheetName: 'Eine Funktion erkunden',
      WorkflowLabel.worksheetGraph: 'Verknüpften Graphen anzeigen',
      WorkflowLabel.worksheetHistory: 'Dokumentverlauf',
      WorkflowLabel.worksheetExport: 'Arbeitsblatt-Exportvorschau',
      WorkflowLabel.worksheetGraphFull: 'Arbeitsblatt erstellt. Alle Graphenplätze sind belegt; leeren Sie einen Platz und zeichnen Sie dann die Funktionszeile.',
      WorkflowLabel.worksheetLinkFailed: 'Arbeitsblatt erstellt, aber der Graph konnte nicht verknüpft werden: {value}',

      WorkflowLabel.calculationProgress:
          'Ergebnisse werden aktualisiert: {value}',
      WorkflowLabel.cancelCalculation: 'Berechnung abbrechen',
      WorkflowLabel.calculationStopped:
          'Berechnung angehalten. Fertige Ergebnisse bleiben erhalten.',
      WorkflowLabel.methodExpansionFallback:
          'Polynomentwicklung als Ersatz; vollständige Vereinfachung nicht verfügbar',
      WorkflowLabel.resultDetails: 'Ergebnisdetails',
      WorkflowLabel.resultExact: 'Exakt',
      WorkflowLabel.resultApproximate: 'Näherung',
      WorkflowLabel.resultSymbolic: 'Symbolisch',
      WorkflowLabel.resultComputed: 'Berechnet',
      WorkflowLabel.resultUnsupported: 'Nicht unterstützt',
      WorkflowLabel.resultUnchanged:
          'Kein verändertes Ergebnis. Der Ausdruck könnte sich dennoch weiter vereinfachen lassen.',
      WorkflowLabel.resultUnknownPrecision:
          'Diese Operation hat keine Genauigkeit angegeben.',
      WorkflowLabel.methodInteger: 'Ganzzahlarithmetik',
      WorkflowLabel.methodPolynomial: 'Exakte Polynomintegration',
      WorkflowLabel.methodRational: 'Integration rationaler Funktionen',
      WorkflowLabel.methodRules: 'Symbolische Integrationsregeln',
      WorkflowLabel.methodFundamental:
          'Stammfunktion an den Grenzen ausgewertet',
      WorkflowLabel.methodSimpson: 'Numerische Integration (Simpson-Regel)',
      WorkflowLabel.methodNumeric: 'Gleitkommaberechnung',
      WorkflowLabel.methodSymbolic: 'Ausdrucksauswertung',
      WorkflowLabel.methodSimplification: 'Vereinfachung',
      WorkflowLabel.methodCalendar: 'Datumsrechnung',
      WorkflowLabel.methodUnits: 'Einheitenumrechnung',
      WorkflowLabel.updatingResults:
          'Ergebnisse werden aktualisiert. Weitere Eingaben sind möglich.',
      WorkflowLabel.resultsFailed:
          'Nicht alle Ergebnisse konnten aktualisiert werden. Berechnung erneut versuchen.',
      WorkflowLabel.editExpression: 'Ausdruck bearbeiten',
      WorkflowLabel.mathPreview: 'Mathematische Vorschau',
      WorkflowLabel.expression: 'Ausdruck',
      WorkflowLabel.resetFocus: 'Tastaturfokus zurücksetzen',
      WorkflowLabel.backspace: 'Rücktaste',
      WorkflowLabel.cursorLeft: 'Cursor nach links',
      WorkflowLabel.cursorRight: 'Cursor nach rechts',
      WorkflowLabel.evaluate: 'Berechnen',
      WorkflowLabel.linkedSource: 'Verknüpfte Quelle für Y{value}',
      WorkflowLabel.sourceExplanation:
          'x ist die Graphvariable. Andere Werte stammen aus dem Quelldokument.',
      WorkflowLabel.editVariable: '{value} bearbeiten',
      WorkflowLabel.detachSource: 'Quelle trennen',
      WorkflowLabel.openSource: 'Quelle öffnen',
      WorkflowLabel.close: 'Schließen',
      WorkflowLabel.mathAssistance: 'Mathematikhilfe',
      WorkflowLabel.configured:
          'Konfiguriert: {value}. Die Verbindung wird nach einer erfolgreichen Anfrage bestätigt.',
      WorkflowLabel.configureProvider:
          'Endpunkt und Modell in den CrispAssist-Einstellungen konfigurieren.',
      WorkflowLabel.mathQuestion: 'Mathematische Frage',
      WorkflowLabel.questionHint: 'z. B. x zum Quadrat integrieren',
      WorkflowLabel.providerNotice:
          'Die Frage wird an den konfigurierten Anbieter gesendet. Übersetzung prüfen; der Rechner berechnet das Ergebnis.',
      WorkflowLabel.reviewExpression:
          'Anbieter hat geantwortet. Ausdruck prüfen oder bearbeiten:',
      WorkflowLabel.translatedExpression: 'Übersetzter Ausdruck',
      WorkflowLabel.cancelRequest: 'Anfrage abbrechen',
      WorkflowLabel.cancelled: 'Anfrage abgebrochen. Erneuter Versuch möglich.',
      WorkflowLabel.translate: 'Übersetzen',
      WorkflowLabel.retry: 'Erneut versuchen',
      WorkflowLabel.useCalculator: 'Im Rechner verwenden',
      WorkflowLabel.clarification: 'Weitere Angaben nötig: {value}',
    },
    'fr': {
      WorkflowLabel.historyCompare: 'Comparer une version',
      WorkflowLabel.historyChanges: 'Modifications depuis cette version :',
      WorkflowLabel.historyNoChanges: 'Aucune modification du texte source',
      WorkflowLabel.historyRestoreNotice: 'La restauration sauvegarde d’abord votre travail actuel, puis recalcule les résultats.',
      WorkflowLabel.historyRestore: 'Restaurer la version',
      WorkflowLabel.historyLimits: 'Jusqu’à 20 versions par document et 100 au total, dans une limite de 1 Mo. Les anciennes versions expirent lorsque la limite est atteinte.',
      WorkflowLabel.historyEmpty: 'Aucune version sauvegardée. Enregistrez-en une pour conserver une version de cette feuille.',
      WorkflowLabel.historySave: 'Enregistrer une version',
      WorkflowLabel.historyBeforeRestore: 'Avant restauration',
      WorkflowLabel.historyCompareButton: 'Comparer',
      WorkflowLabel.cancel: 'Annuler',
      WorkflowLabel.exportSnapshot: 'Instantané des calculs et des graphiques liés. Plage x/y des graphiques : -5 à 5 ; plage x du tableau : -5 à 5.',
      WorkflowLabel.exportFailed: 'Échec de l’export : {value}',
      WorkflowLabel.exportSave: 'Enregistrer {value}',
      WorkflowLabel.exportUndefined: 'Non défini',

      WorkflowLabel.exploreWorksheet: 'Explorer une feuille liée',
      WorkflowLabel.connectedWorksheetName: 'Explorer une fonction',
      WorkflowLabel.worksheetGraph: 'Voir le graphique lié',
      WorkflowLabel.worksheetHistory: 'Historique du document',
      WorkflowLabel.worksheetExport: 'Aperçu de l’export de la feuille',
      WorkflowLabel.worksheetGraphFull: 'Feuille créée. Tous les emplacements de graphique sont occupés ; libérez-en un, puis tracez la ligne de fonction.',
      WorkflowLabel.worksheetLinkFailed: 'Feuille créée, mais le graphique n’a pas pu être lié : {value}',

      WorkflowLabel.calculationProgress: 'Mise à jour des résultats : {value}',
      WorkflowLabel.cancelCalculation: 'Annuler le calcul',
      WorkflowLabel.calculationStopped:
          'Calcul arrêté. Les résultats terminés sont conservés.',
      WorkflowLabel.methodExpansionFallback:
          'Développement polynomial de secours ; simplification complète indisponible',
      WorkflowLabel.resultDetails: 'Détails du résultat',
      WorkflowLabel.resultExact: 'Exact',
      WorkflowLabel.resultApproximate: 'Approximatif',
      WorkflowLabel.resultSymbolic: 'Symbolique',
      WorkflowLabel.resultComputed: 'Calculé',
      WorkflowLabel.resultUnsupported: 'Non pris en charge',
      WorkflowLabel.resultUnchanged:
          'Aucun changement produit. Cela ne prouve pas que l’expression ne peut plus être simplifiée.',
      WorkflowLabel.resultUnknownPrecision:
          'Cette opération n’a pas indiqué sa précision.',
      WorkflowLabel.methodInteger: 'Arithmétique entière',
      WorkflowLabel.methodPolynomial: 'Intégration polynomiale exacte',
      WorkflowLabel.methodRational: 'Intégration de fonctions rationnelles',
      WorkflowLabel.methodRules: 'Règles d’intégration symbolique',
      WorkflowLabel.methodFundamental: 'Primitive évaluée aux bornes',
      WorkflowLabel.methodSimpson: 'Intégration numérique (règle de Simpson)',
      WorkflowLabel.methodNumeric: 'Calcul en virgule flottante',
      WorkflowLabel.methodSymbolic: 'Évaluation d’expression',
      WorkflowLabel.methodSimplification: 'Simplification',
      WorkflowLabel.methodCalendar: 'Calcul de dates',
      WorkflowLabel.methodUnits: 'Conversion d’unités',
      WorkflowLabel.updatingResults:
          'Mise à jour des résultats. Vous pouvez continuer à modifier.',
      WorkflowLabel.resultsFailed:
          'Impossible de mettre à jour tous les résultats. Relancez le calcul.',
      WorkflowLabel.editExpression: 'Modifier l’expression',
      WorkflowLabel.mathPreview: 'Aperçu mathématique',
      WorkflowLabel.expression: 'Expression',
      WorkflowLabel.resetFocus: 'Rétablir le focus du clavier',
      WorkflowLabel.backspace: 'Effacer le caractère',
      WorkflowLabel.cursorLeft: 'Déplacer le curseur à gauche',
      WorkflowLabel.cursorRight: 'Déplacer le curseur à droite',
      WorkflowLabel.evaluate: 'Calculer',
      WorkflowLabel.linkedSource: 'Source liée à Y{value}',
      WorkflowLabel.sourceExplanation:
          'x est la variable du graphique. Les autres valeurs proviennent du document source.',
      WorkflowLabel.editVariable: 'Modifier {value}',
      WorkflowLabel.detachSource: 'Détacher la source',
      WorkflowLabel.openSource: 'Ouvrir la source',
      WorkflowLabel.close: 'Fermer',
      WorkflowLabel.mathAssistance: 'Aide mathématique',
      WorkflowLabel.configured:
          'Configuré : {value}. La connexion est vérifiée après une requête réussie.',
      WorkflowLabel.configureProvider:
          'Configurer un point d’accès et un modèle dans les paramètres CrispAssist.',
      WorkflowLabel.mathQuestion: 'Question mathématique',
      WorkflowLabel.questionHint: 'p. ex. Intégrer x au carré',
      WorkflowLabel.providerNotice:
          'Votre question est envoyée au fournisseur configuré. Vérifiez la traduction ; la calculatrice calcule le résultat.',
      WorkflowLabel.reviewExpression:
          'Réponse reçue. Vérifiez ou modifiez cette expression :',
      WorkflowLabel.translatedExpression: 'Expression traduite',
      WorkflowLabel.cancelRequest: 'Annuler la requête',
      WorkflowLabel.cancelled: 'Requête annulée. Vous pouvez réessayer.',
      WorkflowLabel.translate: 'Traduire',
      WorkflowLabel.retry: 'Réessayer',
      WorkflowLabel.useCalculator: 'Utiliser dans la calculatrice',
      WorkflowLabel.clarification:
          'Informations supplémentaires nécessaires : {value}',
    },
    'es': {
      WorkflowLabel.historyCompare: 'Comparar versión',
      WorkflowLabel.historyChanges: 'Cambios desde esta versión:',
      WorkflowLabel.historyNoChanges: 'Sin cambios en el texto fuente',
      WorkflowLabel.historyRestoreNotice: 'La restauración guarda primero tu trabajo actual y luego recalcula los resultados.',
      WorkflowLabel.historyRestore: 'Restaurar versión',
      WorkflowLabel.historyLimits: 'Hasta 20 versiones por documento y 100 en total, dentro de 1 MB. Las versiones antiguas caducan al alcanzar el límite.',
      WorkflowLabel.historyEmpty: 'Aún no hay versiones. Guarda una para conservar una versión de esta hoja.',
      WorkflowLabel.historySave: 'Guardar versión',
      WorkflowLabel.historyBeforeRestore: 'Antes de restaurar',
      WorkflowLabel.historyCompareButton: 'Comparar',
      WorkflowLabel.cancel: 'Cancelar',
      WorkflowLabel.exportSnapshot: 'Instantánea de cálculos y gráficos vinculados. Rango x/y del gráfico: -5 a 5; rango x de la tabla: -5 a 5.',
      WorkflowLabel.exportFailed: 'Error de exportación: {value}',
      WorkflowLabel.exportSave: 'Guardar {value}',
      WorkflowLabel.exportUndefined: 'No definido',

      WorkflowLabel.exploreWorksheet: 'Explorar una hoja vinculada',
      WorkflowLabel.connectedWorksheetName: 'Explorar una función',
      WorkflowLabel.worksheetGraph: 'Ver gráfico vinculado',
      WorkflowLabel.worksheetHistory: 'Historial del documento',
      WorkflowLabel.worksheetExport: 'Vista previa de exportación',
      WorkflowLabel.worksheetGraphFull: 'Hoja creada. Los espacios de gráficos están llenos; libera uno y luego representa la línea de función.',
      WorkflowLabel.worksheetLinkFailed: 'Hoja creada, pero no se pudo vincular el gráfico: {value}',

      WorkflowLabel.calculationProgress: 'Actualizando resultados: {value}',
      WorkflowLabel.cancelCalculation: 'Cancelar cálculo',
      WorkflowLabel.calculationStopped:
          'Cálculo detenido. Se conservan los resultados completados.',
      WorkflowLabel.methodExpansionFallback:
          'Desarrollo polinómico alternativo; simplificación completa no disponible',
      WorkflowLabel.resultDetails: 'Detalles del resultado',
      WorkflowLabel.resultExact: 'Exacto',
      WorkflowLabel.resultApproximate: 'Aproximado',
      WorkflowLabel.resultSymbolic: 'Simbólico',
      WorkflowLabel.resultComputed: 'Calculado',
      WorkflowLabel.resultUnsupported: 'No compatible',
      WorkflowLabel.resultUnchanged:
          'No se produjo ningún cambio. Esto no demuestra que la expresión no pueda simplificarse más.',
      WorkflowLabel.resultUnknownPrecision:
          'Esta operación no indicó su precisión.',
      WorkflowLabel.methodInteger: 'Aritmética entera',
      WorkflowLabel.methodPolynomial: 'Integración polinómica exacta',
      WorkflowLabel.methodRational: 'Integración de funciones racionales',
      WorkflowLabel.methodRules: 'Reglas de integración simbólica',
      WorkflowLabel.methodFundamental: 'Primitiva evaluada en los límites',
      WorkflowLabel.methodSimpson: 'Integración numérica (regla de Simpson)',
      WorkflowLabel.methodNumeric: 'Cálculo en coma flotante',
      WorkflowLabel.methodSymbolic: 'Evaluación de expresiones',
      WorkflowLabel.methodSimplification: 'Simplificación',
      WorkflowLabel.methodCalendar: 'Cálculo de fechas',
      WorkflowLabel.methodUnits: 'Conversión de unidades',
      WorkflowLabel.updatingResults:
          'Actualizando resultados. Puedes seguir editando.',
      WorkflowLabel.resultsFailed:
          'No se pudieron actualizar todos los resultados. Reintenta el cálculo.',
      WorkflowLabel.editExpression: 'Editar expresión',
      WorkflowLabel.mathPreview: 'Vista matemática',
      WorkflowLabel.expression: 'Expresión',
      WorkflowLabel.resetFocus: 'Restablecer el foco del teclado',
      WorkflowLabel.backspace: 'Borrar carácter',
      WorkflowLabel.cursorLeft: 'Mover cursor a la izquierda',
      WorkflowLabel.cursorRight: 'Mover cursor a la derecha',
      WorkflowLabel.evaluate: 'Calcular',
      WorkflowLabel.linkedSource: 'Fuente vinculada de Y{value}',
      WorkflowLabel.sourceExplanation:
          'x es la variable del gráfico. Los demás valores provienen del documento fuente.',
      WorkflowLabel.editVariable: 'Editar {value}',
      WorkflowLabel.detachSource: 'Desvincular fuente',
      WorkflowLabel.openSource: 'Abrir fuente',
      WorkflowLabel.close: 'Cerrar',
      WorkflowLabel.mathAssistance: 'Ayuda matemática',
      WorkflowLabel.configured:
          'Configurado: {value}. La conexión se verifica tras una solicitud correcta.',
      WorkflowLabel.configureProvider:
          'Configura un punto de acceso y un modelo en los ajustes de CrispAssist.',
      WorkflowLabel.mathQuestion: 'Pregunta matemática',
      WorkflowLabel.questionHint: 'p. ej. Integrar x al cuadrado',
      WorkflowLabel.providerNotice:
          'La pregunta se envía al proveedor configurado. Revisa la traducción; la calculadora calcula el resultado.',
      WorkflowLabel.reviewExpression:
          'El proveedor respondió. Revisa o edita esta expresión:',
      WorkflowLabel.translatedExpression: 'Expresión traducida',
      WorkflowLabel.cancelRequest: 'Cancelar solicitud',
      WorkflowLabel.cancelled: 'Solicitud cancelada. Puedes reintentarlo.',
      WorkflowLabel.translate: 'Traducir',
      WorkflowLabel.retry: 'Reintentar',
      WorkflowLabel.useCalculator: 'Usar en calculadora',
      WorkflowLabel.clarification: 'Se necesita más información: {value}',
    },
  };
}
