#!/usr/bin/env python3
"""Certify test/data/cas_corpus.json against SymPy and regenerate
test/cas_corpus_data.dart.

Every corpus case's `expected` value is re-derived (or equivalence-checked)
with SymPy, an independent open-source CAS, so the Dart test runners assert
against externally verified mathematics — not against what our own engine
happens to return.

Usage:  python3 tool/cas_corpus_verify.py
Exits non-zero (and does NOT regenerate the Dart file) if any case fails.
"""

import json
import sys
from pathlib import Path

import sympy as sp

ROOT = Path(__file__).resolve().parent.parent
CORPUS = ROOT / "test" / "data" / "cas_corpus.json"
DART_OUT = ROOT / "test" / "cas_corpus_data.dart"


def to_sympy(s: str):
    """Engine syntax -> SymPy expression. `^` is power; `log` is ln
    (both already match SymPy); `oo` is infinity."""
    expr = sp.sympify(s.replace("^", "**"), evaluate=True)
    if isinstance(expr, sp.Basic):
        expr = expr.subs(sp.Symbol("e"), sp.E)  # engine syntax: e = Euler's number
    return expr


def equal(a, b) -> bool:
    return sp.simplify(a - b) == 0


def verify(case: dict) -> str | None:
    """Return an error string, or None if the case is certified."""
    op = case["op"]
    exp_raw = case["expected"]

    if op == "evaluate":
        got = to_sympy(case["input"])
        if not equal(got, to_sympy(exp_raw)):
            return f"evaluate: {case['input']} = {got}, corpus says {exp_raw}"
        return None

    if op in ("expand", "simplify"):
        if not equal(to_sympy(case["input"]), to_sympy(exp_raw)):
            return f"{op}: expected not equivalent to input"
        if op == "expand" and to_sympy(exp_raw) != sp.expand(to_sympy(exp_raw)):
            return "expand: corpus expected value is not fully expanded"
        return None

    if op == "factor":
        inp, exp = to_sympy(case["input"]), to_sympy(exp_raw)
        if not equal(inp, exp):
            return "factor: expected not equivalent to input"
        # The expected form must be a genuine factorization, i.e. match
        # SymPy's own factorization up to ordering/sign.
        if not equal(sp.factor(inp), exp):
            return f"factor: SymPy factors to {sp.factor(inp)}, corpus says {exp_raw}"
        return None

    if op == "differentiate":
        x = sp.Symbol(case["var"])
        got = sp.diff(to_sympy(case["input"]), x)
        if not equal(got, to_sympy(exp_raw)):
            return f"diff: d/d{x} = {got}, corpus says {exp_raw}"
        return None

    if op == "integrate":
        x = sp.Symbol(case["var"])
        d = sp.diff(to_sympy(exp_raw), x)
        if not equal(d, to_sympy(case["input"])):
            return f"integrate: d/d{x}(expected) = {d}, integrand is {case['input']}"
        return None

    if op == "integrate_def":
        x = sp.Symbol(case["var"])
        got = sp.integrate(
            to_sympy(case["input"]), (x, to_sympy(case["lo"]), to_sympy(case["hi"]))
        )
        if not equal(got, to_sympy(exp_raw)):
            return f"definite integral = {got}, corpus says {exp_raw}"
        return None

    if op == "limit":
        x = sp.Symbol(case["var"])
        got = sp.limit(to_sympy(case["input"]), x, to_sympy(case["point"]))
        if not equal(got, to_sympy(exp_raw)):
            return f"limit = {got}, corpus says {exp_raw}"
        return None

    if op == "solve":
        x = sp.Symbol(case["var"])
        roots = sp.solveset(to_sympy(case["input"]), x, domain=sp.S.Complexes)
        expected = {to_sympy(r) for r in exp_raw}
        if not isinstance(roots, sp.FiniteSet):
            return f"solve: SymPy returned non-finite set {roots}"
        got = set(roots)
        if len(got) != len(expected):
            return f"solve: {len(got)} roots from SymPy, corpus lists {len(expected)}"
        for e in expected:
            if not any(equal(e, g) for g in got):
                return f"solve: corpus root {e} not among SymPy roots {got}"
        return None

    if op == "substitute":
        x = sp.Symbol(case["var"])
        got = to_sympy(case["input"]).subs(x, to_sympy(case["value"]))
        if not equal(got, to_sympy(exp_raw)):
            return f"substitute -> {got}, corpus says {exp_raw}"
        return None

    if op in ("gcd", "lcm"):
        a, b = (to_sympy(v) for v in case["args"])
        got = sp.gcd(a, b) if op == "gcd" else sp.lcm(a, b)
        if got != to_sympy(exp_raw):
            return f"{op}({a}, {b}) = {got}, corpus says {exp_raw}"
        return None

    return f"unknown op {op!r}"


def emit_dart(raw: str) -> None:
    body = raw.replace("$", r"\$")  # $ would interpolate inside a Dart literal
    DART_OUT.write_text(
        "// GENERATED by tool/cas_corpus_verify.py — DO NOT EDIT.\n"
        "// Source of truth: test/data/cas_corpus.json (SymPy-certified).\n"
        "// Embedded as a string so integration_test runners need no file IO.\n"
        "\n"
        "const String kCasCorpusJson = '''\n"
        f"{body}"
        "''';\n"
    )


def main() -> int:
    raw = CORPUS.read_text()
    cases = json.loads(raw)["cases"]
    ids = [c["id"] for c in cases]
    assert len(ids) == len(set(ids)), "duplicate case ids"

    failures = []
    for case in cases:
        try:
            err = verify(case)
        except Exception as e:  # a crash is a failure too
            err = f"exception: {e}"
        if err:
            failures.append((case["id"], err))
            print(f"FAIL  {case['id']}: {err}")
        else:
            print(f"ok    {case['id']}")

    if failures:
        print(f"\n{len(failures)}/{len(cases)} cases FAILED — Dart data not regenerated.")
        return 1

    emit_dart(raw)
    print(f"\nAll {len(cases)} cases certified. Wrote {DART_OUT.relative_to(ROOT)}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
