name: Deploy Web (WASM) to GitHub Pages

on:
  push:
    branches: [ "main" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CrispCalc
        uses: actions/checkout@v4

      - name: Checkout CrispEmbed
        uses: actions/checkout@v4
        with:
          repository: CrispStrobe/CrispEmbed
          path: ../CrispEmbed

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web (WASM)
        # We enable WASM GC compilation.
        run: flutter build web --wasm --base-href "/CrispMath/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
